# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JLPayNetworkDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'AFNetworking', '~> 3.2.1'

  # Pods for JLPayNetworkDemo

  target 'JLPayNetworkDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JLPayNetworkDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
