# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JLPayNetworkDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'JLPayNetwork', :path => '../'
  pod 'RSAUtil', '~> 1.0'
  pod 'GTMBase64', '~> 1.0.1'
  pod 'KeychainItemWrapper', '~> 1.2'

  # Pods for JLPayNetworkDemo

  target 'JLPayNetworkDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JLPayNetworkDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
